version: "3"

services:
  express:
    container_name: express-container
    build: .
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.1.10
    container_name: mongodb-container
    ports:
      - 27017:27017
